### PR TITLE
jwk: initialize the decoded buffer lengths up front

### PR DESCRIPTION
**Pull request by kraj**
_cjose_jwk_import_EC() and _cjose_jwk_import_RSA() declare their *_buflen variables in the middle of the function, interleaved with error paths that goto the shared cleanup label. When an early decode fails, the goto jumps over the remaining declarations and the cleanup block then reads them uninitialized:

| jwk.c:1501:9: error: variable 'dq_buflen' is used uninitialized
|                whenever 'if' condition is true
|                [-Werror,-Wsometimes-uninitialized]
| jwk.c:1554:39: note: uninitialized use occurs here
|     _cjose_cleanse_dealloc(dq_buffer, dq_buflen);

_cjose_cleanse_dealloc() uses the length to wipe key material, so this is a real out-of-bounds write hazard on the error path, not just a warning. src/Makefile.am builds with -Werror, so it also breaks the build with clang.

Declare the lengths alongside the buffers they pair with and assign them where they were previously initialized.

### CODE REVIEW

**Comment by zandbelt** [comment]
Thanks — reproduced here. `src/jwk.c` is the only file that trips it: with the project's own flags (`-std=gnu99 --pedantic -Wall`, plus the `-Werror` from `src/Makefile.am`) clang emits 27 `-Wsometimes-uninitialized` diagnostics, all of them from `_cjose_jwk_import_RSA()`. GCC 15 stays silent even under `-Wextra`, which is why this got through. With the patch applied all nine sources compile clean under `clang -Wall -Werror` and the full `check_cjose` suite passes.

I bisected it to 1a419a8 ("jwk: cleanse private key material on import/export paths"), the commit that introduced the unconditional `_cjose_cleanse_dealloc()` cleanup block; its parent is clean. So v0.6.2.6 and v0.6.2.7 both ship a tree that can't be built with clang — I'd like to get this in and cut 0.6.2.8.

One change before I merge, on the severity framing in the commit message:

> `_cjose_cleanse_dealloc()` uses the length to wipe key material, so this is a real out-of-bounds write hazard on the error path, not just a warning.

I don't think that part holds:

* `_cjose_cleanse_dealloc()` (`src/util.c:103`) returns immediately when `ptr == NULL`, so the length is never used.
* On every `goto import_RSA_cleanup` path, each still-uninitialized `*_buflen` is paired with a buffer that is `NULL` — the buffers are NULL-initialized at the top of the function, and `_decode_json_object_base64url_attribute()` sets `*buffer = NULL` on its own failure (`src/jwk.c:1355`, `1363`).

An indeterminate length therefore always pairs with a NULL pointer, and no wipe is ever attempted. What remains is still genuine UB — evaluating an indeterminate `size_t` as a function argument (C11 6.3.2.1p2), which is exactly what clang is objecting to — plus a hard build failure under `-Werror`. That is more than enough reason to take the fix, and the invariant keeping it harmless is too implicit to want to rely on. But it isn't an out-of-bounds write, and I'd rather the 0.6.2.8 CHANGELOG not read as though 0.6.2.7 had memory corruption in a pre-auth import path.

Could you reword the body along these lines?

```
jwk: initialize the decoded buffer lengths up front

_cjose_jwk_import_EC() and _cjose_jwk_import_RSA() declare their
*_buflen variables in the middle of the function, interleaved with
error paths that goto the shared cleanup label. When an early decode
fails, the goto jumps over the remaining declarations and the cleanup
block reads them uninitialized:

| jwk.c:1501:9: error: variable 'dq_buflen' is used uninitialized
|                whenever 'if' condition is true
|                [-Werror,-Wsometimes-uninitialized]
| jwk.c:1554:39: note: uninitialized use occurs here
|     _cjose_cleanse_dealloc(dq_buffer, dq_buflen);

No wipe is actually performed with the garbage length: on every error
path the uninitialized length is paired with a NULL buffer, and
_cjose_cleanse_dealloc() returns early on NULL. But evaluating an
indeterminate size_t as a function argument is undefined behaviour,
the invariant that keeps it harmless is not evident from the cleanup
block, and src/Makefile.am builds with -Werror, so this also breaks
the build with clang.

Declare the lengths alongside the buffers they pair with and assign
them where they were previously initialized.
```

Two non-blocking notes:

* The EC hunk doesn't silence anything — `x_buflen`/`y_buflen` are never read in `import_EC_cleanup` (plain `cjose_get_dealloc()`), and `d_buflen` is read only under `if (NULL != d_buffer)`, so clang never flags that function. Fine to keep for symmetry.
* No regression test needed here; there's no observable behavior change to assert on.

On my side: I'll add the CHANGELOG entry when cutting 0.6.2.8, and open a separate PR adding a clang leg to `build.yml`. The gcc-only matrix is the real root cause, and the valgrind step passes `--undef-value-errors=no`, which disables the one check that might otherwise have caught this.

**Comment by zandbelt** [comment]
I've opened #35 with your patch so this can go into 0.6.2.8 — closing here in favour of that.

To be clear about what did and didn't change: **the code is yours and is untouched.** `git diff` between your commit and the one in #35 is empty, and git authorship still records you as the author, with your original author date. The only difference is the commit message, applying the rewording from my earlier comment — dropping the out-of-bounds-write framing while keeping the UB and `-Werror` justification.

I went this route rather than force-pushing over your branch, which seemed the less intrusive option when you hadn't had a chance to reply yet. If you'd rather land it yourself under your own PR, say so and I'll close #35 and take yours instead — no objection at all, the diff is identical either way.

Thanks for catching this. It turned out to be worse than a single warning: bisected to 1a419a8, which shipped in both v0.6.2.6 and v0.6.2.7, so both released tags are unbuildable with clang. It also exposed that CI never built with clang at all — #33 adds that leg, and while measuring it I found the valgrind step had never actually instrumented the test binary either (it was running the libtool wrapper), which #34 sorts out. So your report shook out three fixes rather than one.
